'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class administratorHome

    '''<summary>
    '''totalPendingCaseHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents totalPendingCaseHome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''totalSupportCaseHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents totalSupportCaseHome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''manageApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents manageApproval As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''manageRiderRegistration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents manageRiderRegistration As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''changeCuisineType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents changeCuisineType As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''userManagement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userManagement As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''adminReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adminReport As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''supportIssues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents supportIssues As Global.System.Web.UI.WebControls.Button
End Class
