'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On




Partial Public Class adminstratorManageRegistrations

    '''<summary>
    '''totalPendingCase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents totalPendingCase As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''document_useriID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents document_useriID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''systemAdminRegistration_Approve control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents systemAdminRegistration_Approve As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''systemAdminRegistration_Reject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents systemAdminRegistration_Reject As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''document_restaurantLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents document_restaurantLogo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''document_businessLicense control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents document_businessLicense As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''document_halal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents document_halal As Global.System.Web.UI.WebControls.Label
End Class
