'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class customerHome

    '''<summary>
    '''btnProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnProfile As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHistory As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCart As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbtnDelivery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnDelivery As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnReservation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnReservation As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnDrivethru control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnDrivethru As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbtnSelfCollect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnSelfCollect As Global.System.Web.UI.WebControls.LinkButton
End Class
