'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class notifySupportHome

    Protected WithEvents rptUserSupportSummary As Global.System.Web.UI.WebControls.Repeater


    Protected WithEvents submitNewSupport As Global.System.Web.UI.WebControls.Button

End Class
