'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class restaurantHome

    '''<summary>
    '''restaurantHomeMenuBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents restaurantHomeMenuBar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''restaurantHomeLoginSignup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents restaurantHomeLoginSignup As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''restaurantHomeAddBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents restaurantHomeAddBranch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''restaurantHomeselectBanchRestaurant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents restaurantHomeselectBanchRestaurant As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''restaurantHomeSelectButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents restaurantHomeSelectButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''restaurantHomeEditButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents restaurantHomeEditButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''rptRestaurant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptRestaurant As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblNothing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNothing As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.Button
End Class
