'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class riderDelivery

    '''<summary>
    '''hfLocLatitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfLocLatitude As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfLocLongitude control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfLocLongitude As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hlMap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlMap As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''btnDirectionToRestaurant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDirectionToRestaurant As Global.System.Web.UI.WebControls.Button
End Class
